clc; clear; 
filename = 'um_008withoutsecurity50.xlsm';
sheet = 1;
xlRange = 'B1:B865';
ylRange = 'E1:E865';
nRange = 'G1:G865';
zlRange = 'I1:I865';
out_sod = xlsread(filename,sheet,xlRange) ;
in_sod = xlsread(filename,sheet,ylRange);
num_eventos = xlsread(filename,sheet,nRange);
sum_evento = xlsread(filename,sheet,zlRange);