clc; clear; 
filename = 'um_0.03_50.xlsm';
sheet = 1;
xlRange = 'B1:B697';
ylRange = 'E1:E697';
nRange = 'G1:G697';
zlRange = 'I1:I697';
out_sod = xlsread(filename,sheet,xlRange) ;
in_sod = xlsread(filename,sheet,ylRange);
num_eventos = xlsread(filename,sheet,nRange);
sum_evento = xlsread(filename,sheet,zlRange);